[workspace]
members = [
    "crates/sandbox-interface",
    "crates/sandbox-e2b",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.2.0"
license = "MIT"
authors = ["Futex"]

[workspace.dependencies]
internal-error = { version = "0.1.0", git = "https://github.com/futex-ai/internal-error.git", rev = "6477922a1c4db8c3e35189af69f0147464004b99", package = "internal-error" }
sandbox-e2b = { version = "0.2.0", path = "crates/sandbox-e2b" }
sandbox-interface = { version = "0.2.0", path = "crates/sandbox-interface" }
